notifications:
  email:
    on_success: never
language: cpp
sudo: false
os:
  - osx
env:
  global:
    - NINJA_STATUS="[%p %u/%t@%o %r]"
    - PROJECT_NAME=${PWD##*/}
    - CMAKE_PREFIX_PATH=/usr/local/opt/qt5:$CMAKE_PREFIX_PATH
  matrix:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release
before_install:
  - brew update
  - brew outdated cmake || brew upgrade cmake
  - brew install cppcheck doxygen ninja
# We need to install gcc before hdf5 because otherwise hdf5 will fail.
  # The or statement is a hack to ensure we override the existing gcc without
  # having an error
  - brew install gcc || brew link --overwrite gcc
  - brew install cppcheck doxygen  hdf5 qt5  ninja vtk zeromq
  - brew tap brewsci/homebrew-science
  - brew install brewsci/science/insighttoolkit
  - pip install pyparsing
  - ssh-keyscan bbpcode.epfl.ch >> ~/.ssh/known_hosts
script:
  - mkdir $BUILD_TYPE
  - cd $BUILD_TYPE
  - cmake -GNinja -DCLONE_SUBPROJECTS=ON -DCMAKE_INSTALL_PREFIX=$PWD/install -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
  - ninja all && ninja $PROJECT_NAME-tests && ninja install
